= Notes
include::section-info.adoc


== external course completion upload

=== Option A: Prior to Course Start Date (ideal): 
[%autowidth]
|===
|||

|*is the course listed in the catalog?*
|no
|. Use the Course Submittal Form attached and email it to us at focus@parks.ca.gov 
. Then submit the Section information as below 

If it is 

Please submit this to us prior to the training date(s) so we can set up the Section for you to enroll in. 

Submit to focus@parks.ca.gov  the course name, the facility location (we must have the name and full address), dates, start/end time, capacity limit, provider information (we must have the name, address), cost, and hours and we will add it as a Section that you can submit enrollment for. 

No DPR 392 needed, as it is electronic within FOCUS 

You must register for the course prior to attending on FOCUS (and with the external provider if required), then Submit a Proof of Completion to receive credit after taking the course for it to be added to your training record/history. 



=== Option B: If the training has already occurred: 

 
 

We’re updating the way we handle outside courses since most of them need to be tracked for requirements.  (We have temporarily turned off the Request for Credit option.)  

  
--
Please send us the certificates and the following:  

* the course name
* the facility name/city
* start/end dates
* start/end time 
* provider information
* cost
* total hours
--

|===









In the meantime:  

  
--
Please send us the certificates and the following:  

* the course name
* the facility name/city
* start/end dates
* start/end time 
* provider information
* cost
* total hours
--

cost, 

and the total hours  

 and we will add it as a Section.  
( 

If we don’t have the Course listed in the Catalog, we may ask you to fill out the Course Submittal Form.)   

From there we can enroll you and you can use the Submit Course Completion to upload your certificates and add the courses properly onto your training record.  

 

 

 

Asdfsadfasdfdf 

 

Please complete the Course Submittal Form at https://docs.google.com/forms/d/e/1FAIpQLSc6DQuFUS-MkJW1AS2IHQSH5e6ugdhs126QDKXuwY-19D7VRg/viewform to add the course to the FOCUS catalog. 

  

For your specific instance of training please provide 

Course name 

Facility name 

Facility address 

Start/End date 

Start/End time 

Capacity limit 

Provider name 

Provider address 

Cost 

Hours  

  

We will add it as a Section that you can submit enrollment for.  
